on:
  push:
    branches:
      - main #ここは該当のブランチ
name: Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }} # Secretsと揃える
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}　# Secretsと揃える
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # Secretsと揃える
          LOCAL_DIR: ./
          REMOTE_DIR: /example.com/public_html/example/wp/wp-content/themes/example-theme/
                      # アップロードしたいパスを設定
